
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socks?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver #\u53BB\u6389pom\u4E2D\u7684runtime\u5373\u53EF
server:
  port: 8082
mybatis:
  configuration:
    map-underscore-to-camel-case: true #\u5F00\u542F\u9A7C\u5CF0\u6620\u5C04